config/routes.rb
Cmf::Application.routes.draw do

  # --- Home --- #
  get "users_profile" => "profile#users_profile", :as => "users_profile"
  scope "/profile" do
    get "/" => "profile#profile", :as => "profile"
    get "/data" => "profile#data", :as => "pf_get_data"
    post "/pic" => "profile#set_main_pic", :as => "pf_set_img", :constraints => { provider: /\w+/ }
    post "/name" => "profile#set_name", :as => "pf_set_name", :constraints => { provider: /\w+/ }
    post "/save" => "profile#save", :as => "pf_save", :constraints => { name: /\w+/, email: /.+@.+\.\w+/, price: /\d+/ }
  end
  get "usr/:username" => "profile#public_profile", :as => "public_profile", :constraints  => { :username => /[\w_\-\.]+/}

  # --- Payments --- #
  scope "/payments" do
    get "/new" => "payments#new", :as => "new_payment"
    post "/create" => "payments#create", :as => "new_payment"
    get "/result/:id/:random" => "payments#payment_router", :as => "payment_router"
  end

  # --- Messages --- #
  resources :messages, :only => :create
  scope "/messages" do
    get "/new/:username" => "messages#new", :as => "new_message", :constraints  => { :username => /[\w_\-\.]+/}
    get "/new/:payment_id/:payment_random" => "messages#new"
  end

  # --- Answers --- #
  resources :answers, :except => :new
  get "answers/:username/:token" => "answers#new", :as => "new_answer", :constraints  => { :username => /[\w_\-\.]*/}
  get "evaluate/:id/:token" => "answers#evaluate_answer", :as => "evaluate_answer"
  put "set_evaluation/:id" => "answers#set_evaluation", :as => "set_evaluation"

  # --- Auth Providers --- #
  match "auth/:provider/callback" => "auth_providers#auth_callback"

  # --- Register(Sign Up) --- #
  scope "r" do
    get   "signup"    =>  "sign_up_steps#enter_wizard"      ,  :as => "signup_wizard"
    get   "threshold" =>  "sign_up_steps#step_set_threshold",  :as => "step_set_threshold"
    post  "threshold" =>  "sign_up_steps#step_set_threshold",  :as => "step_set_threshold"
    get   "network"   =>  "sign_up_steps#step_set_network",    :as => "step_set_network"
  end

  # --- Users --- #
  resources :users, :only => [:destroy]
  authenticated :user do
    root :to => 'profile#profile'
  end

  root :to => "profile#index"
  devise_for :users, :path => "auth", :controllers => { sessions: "sessions" }
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :message_id, :response_time, :text, :utility
  belongs_to :message

  validates :text , :presence => true, :on => :create
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :find_message, :except => [ :create, :set_evaluation]
  layout "public"

  def index
    @answers = Answer.all
  end

  def show
  end

  def new
    @user = User.find_by_username(params[:username])
    @answer = Answer.new
  end

  def edit
  end

  def create
    @answer = Answer.new(params[:answer])
    @message = @answer.message
    if @answer.save
      UserMailer.requester_notification(@message.requester_email,@answer.id).deliver
      redirect_to root_path, notice: 'Your answer has been delivered.'
    else
      render action: "new"
    end
  end

  def update
    if @answer.update_attributes(params[:answer])
      redirect_to @answer, notice: 'Answer was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @answer.destroy
    redirect_to answers_url
  end

  def evaluate_answer
    @answer = Answer.find(params[:id])
    redirect_to root_path, :flash => { :error => "Sorry, couldn't find your petition" } if @answer.message.id != @message.id
  end

  def set_evaluation
    @answer = Answer.find(params[:id])
    @message = @answer.message
    if @answer.update_attributes(params[:answer])
      redirect_to root_path, notice: 'Thanks for evaluate the experience!'
    else
      render action: "evaluate_answer"
    end
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_message
    @message = Message.find_by_secure_token(params[:token])
    if @message.nil?
      flash[:error] = "We couldn't find your petition, please try again"
      redirect_to root_path and return
    end
  end

end

app/views/answers/_form.html.haml
= simple_form_for(@answer) do |f|
  = f.error_notification
  %p
    .form-inputs.form-horizontal
      = hidden_field_tag :username, params[:username], :name => "username"
      .control-group
        = f.input :message_id, :as => "hidden", :input_html => { :value => @message.id }
      .control-group
        = f.input :text, :as => "text", :label => "Write your Answer" ,:input_html => { :rows => 5, :style => "width:380px" }
    .row
      .span4.offset2
        = f.button :submit, "Send Answer", :class => "btn btn-primary btn-large"

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/evaluate_answer.html.haml
= simple_form_for(@answer, :url => set_evaluation_path(@answer)) do |f|
  = f.error_notification

  .hero-unit
    %h3 Evaluate this answer:
    .alert.alert-info.small=@answer.text
    %p
    .form-inputs.form-horizontal
      .control-group.evaluation_radio
        = f.input :utility, collection: 1..5, prompt: "Select your evaluation", :as => :radio
      .control-group.evaluation_radio
        = f.input :response_time, collection: 1..5, prompt: "Select your evaluation", :as => :radio
    .row
      .span4.offset2
        = f.button :submit, "Evaluate the Answer" ,:class => "btn btn-success btn-large"

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %tr
    %th Message
    %th Text
    %th Utility
    %th Response time
    %th
    %th
    %th

  - @answers.each do |answer|
    %tr
      %td= answer.message_id
      %td= answer.text
      %td= answer.utility
      %td= answer.response_time
      %td= link_to 'Show', answer
      %td= link_to 'Edit', edit_answer_path(answer)
      %td= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
.container
  .row-fluid
    .well
      %h3
        The message reads:
      %span.comillas> "
      = @message.message
      %span.comillas "
      %h3 Your answer
      You can use the form below or write directly to
      %a{mailto: @message.requester_email} #{@message.requester_email}
      = render 'form'

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @answer.message_id
%p
  %b Text:
  = @answer.text
%p
  %b Utility:
  = @answer.utility
%p
  %b Response time:
  = @answer.response_time

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path