config/routes.rb
Cmf::Application.routes.draw do

  # --- Home --- #
  get "users_profile" => "profile#users_profile", :as => "users_profile"
  scope "/profile" do
    get "/" => "profile#profile", :as => "profile"
    get "/data" => "profile#data", :as => "pf_get_data"
    post "/pic" => "profile#set_main_pic", :as => "pf_set_img", :constraints => { provider: /\w+/ }
    post "/name" => "profile#set_name", :as => "pf_set_name", :constraints => { provider: /\w+/ }
    post "/save" => "profile#save", :as => "pf_save", :constraints => { name: /\w+/, email: /.+@.+\.\w+/, price: /\d+/ }
  end
  get "usr/:username" => "profile#public_profile", :as => "public_profile", :constraints  => { :username => /[\w_\-\.]+/}

  # --- Payments --- #
  scope "/payments" do
    get "/new" => "payments#new", :as => "new_payment"
    post "/create" => "payments#create", :as => "new_payment"
    get "/result/:id/:random" => "payments#payment_router", :as => "payment_router"
  end

  # --- Messages --- #
  resources :messages, :only => :create
  scope "/messages" do
    get "/new/:username" => "messages#new", :as => "new_message", :constraints  => { :username => /[\w_\-\.]+/}
    get "/new/:payment_id/:payment_random" => "messages#new"
  end

  # --- Answers --- #
  resources :answers, :except => :new
  get "answers/:username/:token" => "answers#new", :as => "new_answer", :constraints  => { :username => /[\w_\-\.]*/}
  get "evaluate/:id/:token" => "answers#evaluate_answer", :as => "evaluate_answer"
  put "set_evaluation/:id" => "answers#set_evaluation", :as => "set_evaluation"

  # --- Auth Providers --- #
  match "auth/:provider/callback" => "auth_providers#auth_callback"

  # --- Register(Sign Up) --- #
  scope "r" do
    get   "signup"    =>  "sign_up_steps#enter_wizard"      ,  :as => "signup_wizard"
    get   "threshold" =>  "sign_up_steps#step_set_threshold",  :as => "step_set_threshold"
    post  "threshold" =>  "sign_up_steps#step_set_threshold",  :as => "step_set_threshold"
    get   "network"   =>  "sign_up_steps#step_set_network",    :as => "step_set_network"
  end

  # --- Users --- #
  resources :users, :only => [:destroy]
  authenticated :user do
    root :to => 'profile#profile'
  end

  root :to => "profile#index"
  devise_for :users, :path => "auth", :controllers => { sessions: "sessions" }
end

app/controllers/sign_up_steps_controller.rb
class SignUpStepsController < ApplicationController
  layout "public"

  def index
  end

  def enter_wizard
  	if current_user
  		flash[:notice] = "If you wish to register another user, sign out first"
  		redirect_to profile_path and return 
  	end
  	redirect_to step_set_threshold_path
  end

  def step_set_threshold
  	return unless threshold = params[:threshold]
    @user = User.new
    @user.threshold = threshold
    raise "Couldn't save" unless @user.set_threshold
    session[:user_id] = @user.id
    redirect_to step_set_network_path
  end

  def step_set_network
  end
end

app/views/sign_up_steps/index.html.haml
.container.home
  .home-int
    .row-fluid
      .span6
        .logo
          Toc-Toc!
        .txt-one
          %h1 Set a price tag, commit to answering.
          %hr/
          %h2 You get a lot of bogus offers, so you set a threshold of, say, $5. Someone really interested in contacting you pays for the chance of doing so. You answer his inquiry in a timely manner.
        .btn-home
          %button#start.btn.btn-site{:type => "button"} Set your threshold
      .span6
        .peephole
          %img{:src => image_path("peephole01.png")}/
  .clearfix

  - content_for :javascript do
    :plain
      $("#start").click(function(){
        document.location = "#{signup_wizard_path}"
      });

app/views/sign_up_steps/set_social_networks.html.haml
.jumbotron
	= render 'layouts/messages'
	%h1 3) Link your public profiles
	%p.lead 
		Displaying links to your public profiles will help proving you're you.
		%br
		%strong Important
		MyThreshold.com does *NOT* post, comment, or create any content whatsoever on your social networks. If you don't tell your acquintances you are here, they won't know it.

.row-fluid
	.span12
		%em Linking more social networks will improve the probability of someone paying to contact you.
.row-fluid 
	.span4
		= link_to image_tag("authicons/facebook_256.png"), "/auth/facebook"
	.span4
		= link_to image_tag("authicons/twitter_256.png"), "/auth/twitter"
	.span7
		=raw "&nbsp;"

app/views/sign_up_steps/step_set_network.html.haml
.container
  .row-fluid
    .well.box-forms
      .progress.progress-striped.active
        .bar{:style=>"width: 40%;"}
      %h3 2) Choose your password
      %p.lead 
        Select one of the following as your password.
        %br
        %strong Important
        %em MyThreshold.com does *NOT* post, comment, or create any content whatsoever on your social networks.

        #remote
          #services.form-vertical
            = link_to image_tag("authicons/facebook_128.png"), "/auth/facebook"
            = link_to image_tag("authicons/twitter_128.png"), "/auth/twitter"
            = link_to image_tag("authicons/google_128.png"), "/auth/google_oauth2"
            = link_to image_tag("authicons/linkedin_128.png"), "/auth/linkedin"
            = link_to image_tag("authicons/github_128.png"), "/auth/github"

- content_for :breadcrumbs do
  %a{:href => "#"} Sign up
  %span.divider >
  %a.active{:href => "#"} Log in


/
  .jumbotron
    = render 'layouts/messages'
    %h1 3) Link your public profiles
    %p.lead 
      Displaying links to your public profiles will help proving you're you.
      %br
      %strong Important
      MyThreshold.com does *NOT* post, comment, or create any content whatsoever on your social networks. If you don't tell your acquintances you are here, they won't know it.

  .row-fluid
    .span12
      %em Linking more social networks will improve the probability of someone paying to contact you.
  .row-fluid 
    .span4
      = link_to image_tag("authicons/facebook_256.png"), "/auth/facebook"
    .span4
      = link_to image_tag("authicons/twitter_256.png"), "/auth/twitter"
    .span7
      =raw "&nbsp;"

app/views/sign_up_steps/step_set_threshold.html.haml
.container
  .row-fluid
    .well.box-forms
      .progress.progress-striped.active
        .bar{:style=>"width: 20%;"}
      %h3 1) Set a price tag
      %p.lead I commit to answer to anyone who pays...
      = form_tag step_set_threshold_path do
        .input-prepend.input-append
          %span.add-on $
          = text_field_tag :threshold, params[:threshold]
          %span.add-on .00
        = submit_tag "Continue", :class => "btn btn-site"

- content_for :breadcrumbs do
  %a{:href => "#"} Sign up
  %span.divider >
  %a.active{:href => "#"} Set price

/
  .jumbotron
    = render 'layouts/messages'
    %h1 1) Set a price tag
    %p.lead I commit to answer to anyone who pays...
    = form_tag step_set_threshold_path do
      .input-prepend.input-append
        %span.add-on $
        = text_field_tag :threshold, params[:threshold]
        %span.add-on .00
      = submit_tag "Continue", :class => "btn btn-site"