config/routes.rb
Cmf::Application.routes.draw do

  # --- Home --- #
  get "users_profile" => "profile#users_profile", :as => "users_profile"
  scope "/profile" do
    get "/" => "profile#profile", :as => "profile"
    get "/data" => "profile#data", :as => "pf_get_data"
    post "/pic" => "profile#set_main_pic", :as => "pf_set_img", :constraints => { provider: /\w+/ }
    post "/name" => "profile#set_name", :as => "pf_set_name", :constraints => { provider: /\w+/ }
    post "/save" => "profile#save", :as => "pf_save", :constraints => { name: /\w+/, email: /.+@.+\.\w+/, price: /\d+/ }
  end
  get "usr/:username" => "profile#public_profile", :as => "public_profile", :constraints  => { :username => /[\w_\-\.]+/}

  # --- Payments --- #
  scope "/payments" do
    get "/new" => "payments#new", :as => "new_payment"
    post "/create" => "payments#create", :as => "new_payment"
    get "/result/:id/:random" => "payments#payment_router", :as => "payment_router"
  end

  # --- Messages --- #
  resources :messages, :only => :create
  scope "/messages" do
    get "/new/:username" => "messages#new", :as => "new_message", :constraints  => { :username => /[\w_\-\.]+/}
    get "/new/:payment_id/:payment_random" => "messages#new"
  end

  # --- Answers --- #
  resources :answers, :except => :new
  get "answers/:username/:token" => "answers#new", :as => "new_answer", :constraints  => { :username => /[\w_\-\.]*/}
  get "evaluate/:id/:token" => "answers#evaluate_answer", :as => "evaluate_answer"
  put "set_evaluation/:id" => "answers#set_evaluation", :as => "set_evaluation"

  # --- Auth Providers --- #
  match "auth/:provider/callback" => "auth_providers#auth_callback"

  # --- Register(Sign Up) --- #
  scope "r" do
    get   "signup"    =>  "sign_up_steps#enter_wizard"      ,  :as => "signup_wizard"
    get   "threshold" =>  "sign_up_steps#step_set_threshold",  :as => "step_set_threshold"
    post  "threshold" =>  "sign_up_steps#step_set_threshold",  :as => "step_set_threshold"
    get   "network"   =>  "sign_up_steps#step_set_network",    :as => "step_set_network"
  end

  # --- Users --- #
  resources :users, :only => [:destroy]
  authenticated :user do
    root :to => 'profile#profile'
  end

  root :to => "profile#index"
  devise_for :users, :path => "auth", :controllers => { sessions: "sessions" }
end

app/views/layouts/_messages.html.haml
- unless flash.empty?
	.container
		.row
			.span7
				- flash.each do |name, msg|
					- if msg.is_a?(String)
						%div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
							%a.close{"data-dismiss" => "alert"} ×
							= content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav.nav-pills.pull-right
  %li{ :class => :active }
    = link_to "Home", root_path
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Profile', profile_path#edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up',"#"# new_user_auth_path
  - if Rails.env.development?
    %li
      = link_to "Public Profiles (Only Development)", users_profile_path

%h3.muted My threshold

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
			%title= content_for?(:title) ? yield(:title) : "My threshold"
			%meta{:content => content_for?(:description) ? yield(:description) : "Cmf", :name => "description"}
				= stylesheet_link_tag "application", :media => "all"
				= javascript_include_tag "application"
				= csrf_meta_tags
				= yield(:head)
	%body
		:css
			body {
				padding-top: 20px;
				padding-bottom: 40px;
			}
			/* Custom container */
			.container-narrow {
				margin: 0 auto;
				max-width: 700px;
			}
			.container-narrow > hr {
				margin: 30px 0;
			}
			/* Main marketing message and sign up button */
			.jumbotron {
				margin: 60px 0;
				text-align: center;
			}
			.jumbotron h1 {
				font-size: 72px;
				line-height: 1;
			}
			.jumbotron .btn {
				font-size: 21px;
				padding: 14px 24px;
			}
			/* Supporting marketing content */
			.marketing {
				margin: 60px 0;
			}
			.marketing p + h4 {
				margin-top: 28px;
			}

		.container-narrow
			.masthead
				= render 'layouts/navigation'
			%hr
			=yield
			%hr
			%footer

app/views/layouts/public.html.haml
!!!
/[if lt IE 7] <html class="no-js ie6 oldie" lang="en">
/[if IE 7] <html class="no-js ie7 oldie" lang="en">
/[if IE 8] <html class="no-js ie8 oldie" lang="en">
/[if IE 9] <html class="no-js ie9 oldie" lang="en">
/ [if gt IE 9]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:name => "charset", :content => "utf-8" }/
    %title TocToc
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0" }/
    %meta{:name => "description", :content => "omg" }/
    %meta{:name => "author", :content => "omg" }/
    = csrf_meta_tags

    = stylesheet_link_tag "application"
    = stylesheet_link_tag params[:controller]
    %link{:href => "http://fonts.googleapis.com/css?family=Oxygen:400,300,700&subset=latin,latin-ext", :rel => "stylesheet"}/
    /[if lt IE 9]
      %script{:type => "text/javascript", :src => "js/html5shiv.js"}
    %link{:href => "img/apple-touch-icon-144-precomposed.png", :sizes => "144x144", :rel => "apple-touch-icon-precomposed"}
    %link{:href => "img/apple-touch-icon-114-precomposed.png", :sizes => "114x114", :rel => "apple-touch-icon-precomposed"}
    %link{:href => "img/apple-touch-icon-72-precomposed.png", :sizes => "72x72", :rel => "apple-touch-icon-precomposed"}
    %link{:href => "img/apple-touch-icon-57-precomposed.png", :rel => "apple-touch-icon-precomposed"}
    /%link{:rel => "shortcut icon", :href => asset_path("favicon.png")}
    :css
      #{yield :style}
  %body
    .navbar.menu-principal
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %a.brand{:href=>"/"} TocToc
        .nav-collapse.collapse
          %ul.nav
            %li{:class => (in_edit_profile ? "active" : "")}
              = link_to "My Profile", profile_path
            - if user_signed_in?
              - if current_user.signed_up?
                %li{:class => (in_my_public_profile ? "active" : "")}
                  = link_to "View Profile", public_profile_path(current_user.username), :id => :public_profile_link
            - else
              %li{:class => (in_login ? "active" : "")}
                = link_to "Login", new_user_session_path
          - if user_signed_in?
            %ul.nav.pull-right
              %li#fat-menu.dropdown
                %a#drop3.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu{"aria-labelledby" => "drop3", :role => "menu"}
                  %li{:role => "presentation"}
                    = link_to "[AlphaOnly] Destroy", user_path(current_user), :method => :delete, :role => "menuitem", :tabindex => "-1"
                  %li.divider{:role => "presentation"}
                  %li{:role => "presentation"}
                    - if user_signed_in?
                      = link_to "Close session", destroy_user_session_path, :method => :delete, :role => "menuitem", :tabindex => "-1"
                    - else
                      = link_to "Login", new_user_session_path, :role => "menuitem", :tabindex => "-1"
    .bg.breadcrumb
      .container
        %ul.breadcrumb
          %li
            - if params[:controller] =~ /steps/ and params[:action] == "index"
              %a{:href => "#"} Home
            - else
              %a{:href => "/"} Home
              %span.divider >
              = yield :breadcrumbs
    = yield
    = javascript_include_tag "application"
    :javascript
      $(function(){
        csrf = $('meta[name="csrf-token"]').attr('content');
        $.ajaxSetup({
          beforeSend: function(xhr) {
            xhr.setRequestHeader('X-CSRF-Token', csrf);
          }
        });
        #{yield :javascript}
      });